# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Enter the Dankmire
email: stankydanko.mc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Cthulhu doesn't always smoke, 
  but when he does, 
  he always smokes StankyDanko 🌿 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danko.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stankydanko
github_username:  stankydanko

# Build settings
theme: minima
plugins:
  - jekyll-feed

firebase:
  apiKey: AIzaSyBXaY6hn6NDJI6WEy1mvtGRXl6V5_W7HJs
  authDomain: "sd-opinion-statements.firebaseapp.com"
  projectId: sd-opinion-statements
  storageBucket: "YOUR_PROJECT_ID.appspot.com"
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID"
  appId: "YOUR_APP_ID"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
